### ISSUE TITLE
Ability to restore document state

### ISSUE THREAD

**Issue by sandersonet** [aptible/ember-json-schema#18]
We should be able to "resume" a document by allowing new instantiations of `Document` to accept a default state.

**Comment by rwjblue** [comment]
Output was renamed from `toJSON` to `dump` in https://github.com/aptible/ember-json-schema/pull/31 in preparation for this operation which I would like to call `load`. 

Any objections?

**Comment by sandersonet** [comment]
Sounds great!

**Comment by sandersonet** [comment]
Fixed by https://github.com/aptible/ember-json-schema/pull/40
