### ISSUE TITLE
Enable Document model to be observable.

### ISSUE THREAD

**Issue by rwjblue** [aptible/ember-json-schema#5]

**Comment by rwjblue** [comment]
As of right now, it is not observable.  We should evaluate if calling `this.rerender()` as needed in consuming components is good enough (and not needless clutter), or if we want to change `Document` base class to extend from `Ember.Object` and call `notifyPropertyChange` as needed internally.

**Comment by sandersonet** [comment]
Closed by https://github.com/aptible/ember-json-schema/pull/8
